<script>
    try {
        var a = ["34", "32", "5", "31", "24", "44", "67"]; //a is an array  
        document.write(a);    // displays elements of a  
        document.write(b); //b is undefined but still trying to fetch its value. Thus catch block will be invoked  
    } catch (e) {
        alert("There is error which shows " + e.message); //Handling error  
    }  
</script>

<script>
    try {
        throw new Error('This is the throw keyword'); //user-defined throw statement.  
    }
    catch (e) {
        document.write(e.message); // This will generate an error message  
    }  
</script>


<script>
    function addition(a,b){
        try{
            let name = true;
            name.reverse();
        }catch(err){
            console.log(err);
        }
        finally{
            console.log("yes");
        }
    }
    addition(1,-2);
    let result = 5;
    console.log(result);
</script>